name: Update ETF Data

on:
  schedule:
    - cron: "30 11 * * 1-5"  # At 11:30 AM UTC (5:00 PM IST) on weekdays (Monday-Friday)
  workflow_dispatch:

# Set the permissions at the workflow level
permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This will use the default GITHUB_TOKEN
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install yfinance

      - name: Fetch ETF Data
        run: python etf52.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the file
          git add data.json
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Update ETF data"
            git push
          else
            echo "No changes to commit"
          fi