name: Update ETF Data

on:
  schedule:
    - cron: "30 11 * * 1-5"  # At 11:30 AM UTC (5:00 PM IST) on weekdays (Monday-Friday)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install yfinance

      - name: Fetch ETF Data
        run: python etf52.py

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /github/workspace
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}
          git pull
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ETF data"
          git push